/*
 * atoms.h - アトムの一覧と _NET_SUPPORTED のゲーティング (SPEC §5.2.1)
 *
 * ATOM_LIST は X-macro。第 2 引数が「_NET_SUPPORTED に載せるか」を決める:
 *   SUP  = 実装済みでテストがある。_NET_SUPPORTED に載せる
 *   KNOWN= 内部で使うが載せない（未実装、またはテスト未整備、または WM の管轄外）
 *
 * フェーズが進んで実装とテストが揃ったら KNOWN → SUP に昇格させる。
 * CI (tools/check-supported.sh) が「SUP なのにテストが無い」を検出する。
 */
#ifndef ATOMS_H
#define ATOMS_H

#include <xcb/xcb.h>

#define ATOM_KNOWN 0
#define ATOM_SUP   1

/*  X(識別子, サポート状態, 文字列)  */
#define ATOM_LIST(X) \
	/* ---- ICCCM ---- */ \
	X(WM_STATE,                     ATOM_KNOWN, "WM_STATE") \
	X(WM_PROTOCOLS,                 ATOM_KNOWN, "WM_PROTOCOLS") \
	X(WM_DELETE_WINDOW,             ATOM_KNOWN, "WM_DELETE_WINDOW") \
	X(WM_TAKE_FOCUS,                ATOM_KNOWN, "WM_TAKE_FOCUS") \
	X(WM_CHANGE_STATE,              ATOM_KNOWN, "WM_CHANGE_STATE") \
	X(WM_CLIENT_LEADER,             ATOM_KNOWN, "WM_CLIENT_LEADER") \
	X(WM_CLIENT_MACHINE,            ATOM_KNOWN, "WM_CLIENT_MACHINE") \
	X(WM_COLORMAP_WINDOWS,          ATOM_KNOWN, "WM_COLORMAP_WINDOWS") \
	/* ---- 型 ---- */ \
	X(UTF8_STRING,                  ATOM_KNOWN, "UTF8_STRING") \
	X(COMPOUND_TEXT,                ATOM_KNOWN, "COMPOUND_TEXT") \
	X(MANAGER,                      ATOM_KNOWN, "MANAGER") \
	/* ---- EWMH ルート ---- */ \
	X(NET_SUPPORTED,                ATOM_SUP,   "_NET_SUPPORTED") \
	X(NET_SUPPORTING_WM_CHECK,      ATOM_SUP,   "_NET_SUPPORTING_WM_CHECK") \
	X(NET_CLIENT_LIST,              ATOM_SUP,   "_NET_CLIENT_LIST") \
	X(NET_CLIENT_LIST_STACKING,     ATOM_SUP,   "_NET_CLIENT_LIST_STACKING") \
	X(NET_NUMBER_OF_DESKTOPS,       ATOM_SUP,   "_NET_NUMBER_OF_DESKTOPS") \
	X(NET_CURRENT_DESKTOP,          ATOM_SUP,   "_NET_CURRENT_DESKTOP") \
	X(NET_DESKTOP_NAMES,            ATOM_SUP, "_NET_DESKTOP_NAMES") \
	X(NET_DESKTOP_GEOMETRY,         ATOM_SUP, "_NET_DESKTOP_GEOMETRY") \
	X(NET_DESKTOP_VIEWPORT,         ATOM_SUP, "_NET_DESKTOP_VIEWPORT") \
	X(NET_WORKAREA,                 ATOM_SUP, "_NET_WORKAREA") \
	X(NET_ACTIVE_WINDOW,            ATOM_SUP,   "_NET_ACTIVE_WINDOW") \
	X(NET_CLOSE_WINDOW,             ATOM_SUP,   "_NET_CLOSE_WINDOW") \
	X(NET_MOVERESIZE_WINDOW,        ATOM_SUP, "_NET_MOVERESIZE_WINDOW") \
	X(NET_WM_MOVERESIZE,            ATOM_SUP, "_NET_WM_MOVERESIZE") \
	X(NET_RESTACK_WINDOW,           ATOM_SUP, "_NET_RESTACK_WINDOW") \
	X(NET_REQUEST_FRAME_EXTENTS,    ATOM_SUP, "_NET_REQUEST_FRAME_EXTENTS") \
	X(NET_SHOWING_DESKTOP,          ATOM_SUP, "_NET_SHOWING_DESKTOP") \
	/* ---- EWMH クライアント ---- */ \
	X(NET_WM_NAME,                  ATOM_SUP,   "_NET_WM_NAME") \
	X(NET_WM_ICON_NAME,             ATOM_KNOWN, "_NET_WM_ICON_NAME") \
	X(NET_WM_VISIBLE_NAME,          ATOM_KNOWN, "_NET_WM_VISIBLE_NAME") \
	X(NET_WM_DESKTOP,               ATOM_SUP, "_NET_WM_DESKTOP") \
	X(NET_WM_PID,                   ATOM_KNOWN, "_NET_WM_PID") \
	X(NET_WM_USER_TIME,             ATOM_SUP, "_NET_WM_USER_TIME") \
	X(NET_WM_USER_TIME_WINDOW,      ATOM_KNOWN, "_NET_WM_USER_TIME_WINDOW") \
	X(NET_FRAME_EXTENTS,            ATOM_SUP, "_NET_FRAME_EXTENTS") \
	X(NET_WM_ICON,                  ATOM_SUP, "_NET_WM_ICON") \
	X(NET_WM_STRUT,                 ATOM_SUP, "_NET_WM_STRUT") \
	X(NET_WM_STRUT_PARTIAL,         ATOM_SUP, "_NET_WM_STRUT_PARTIAL") \
	X(NET_WM_ALLOWED_ACTIONS,       ATOM_SUP, "_NET_WM_ALLOWED_ACTIONS") \
	X(NET_WM_FULLSCREEN_MONITORS,   ATOM_KNOWN, "_NET_WM_FULLSCREEN_MONITORS") \
	X(NET_WM_SYNC_REQUEST,          ATOM_SUP, "_NET_WM_SYNC_REQUEST") \
	X(NET_WM_SYNC_REQUEST_COUNTER,  ATOM_SUP, "_NET_WM_SYNC_REQUEST_COUNTER") \
	X(NET_WM_PING,                  ATOM_SUP, "_NET_WM_PING") \
	/* ---- ウィンドウ種別 (§5.2.2 の enum win_type と同順) ---- */ \
	X(NET_WM_WINDOW_TYPE,           ATOM_SUP,   "_NET_WM_WINDOW_TYPE") \
	X(NET_WM_WINDOW_TYPE_DESKTOP,   ATOM_SUP,   "_NET_WM_WINDOW_TYPE_DESKTOP") \
	X(NET_WM_WINDOW_TYPE_DOCK,      ATOM_SUP,   "_NET_WM_WINDOW_TYPE_DOCK") \
	X(NET_WM_WINDOW_TYPE_TOOLBAR,   ATOM_SUP,   "_NET_WM_WINDOW_TYPE_TOOLBAR") \
	X(NET_WM_WINDOW_TYPE_MENU,      ATOM_SUP,   "_NET_WM_WINDOW_TYPE_MENU") \
	X(NET_WM_WINDOW_TYPE_UTILITY,   ATOM_SUP,   "_NET_WM_WINDOW_TYPE_UTILITY") \
	X(NET_WM_WINDOW_TYPE_SPLASH,    ATOM_SUP,   "_NET_WM_WINDOW_TYPE_SPLASH") \
	X(NET_WM_WINDOW_TYPE_DIALOG,    ATOM_SUP,   "_NET_WM_WINDOW_TYPE_DIALOG") \
	X(NET_WM_WINDOW_TYPE_DROPDOWN_MENU, ATOM_SUP, "_NET_WM_WINDOW_TYPE_DROPDOWN_MENU") \
	X(NET_WM_WINDOW_TYPE_POPUP_MENU,    ATOM_SUP, "_NET_WM_WINDOW_TYPE_POPUP_MENU") \
	X(NET_WM_WINDOW_TYPE_TOOLTIP,       ATOM_SUP, "_NET_WM_WINDOW_TYPE_TOOLTIP") \
	X(NET_WM_WINDOW_TYPE_NOTIFICATION,  ATOM_SUP, "_NET_WM_WINDOW_TYPE_NOTIFICATION") \
	X(NET_WM_WINDOW_TYPE_COMBO,     ATOM_SUP,   "_NET_WM_WINDOW_TYPE_COMBO") \
	X(NET_WM_WINDOW_TYPE_DND,       ATOM_SUP,   "_NET_WM_WINDOW_TYPE_DND") \
	X(NET_WM_WINDOW_TYPE_NORMAL,    ATOM_SUP,   "_NET_WM_WINDOW_TYPE_NORMAL") \
	/* ---- 状態 ---- */ \
	X(NET_WM_STATE,                 ATOM_SUP,   "_NET_WM_STATE") \
	X(NET_WM_STATE_MODAL,           ATOM_KNOWN, "_NET_WM_STATE_MODAL") \
	X(NET_WM_STATE_STICKY,          ATOM_KNOWN, "_NET_WM_STATE_STICKY") \
	X(NET_WM_STATE_MAXIMIZED_VERT,  ATOM_KNOWN, "_NET_WM_STATE_MAXIMIZED_VERT") \
	X(NET_WM_STATE_MAXIMIZED_HORZ,  ATOM_KNOWN, "_NET_WM_STATE_MAXIMIZED_HORZ") \
	X(NET_WM_STATE_SHADED,          ATOM_KNOWN, "_NET_WM_STATE_SHADED") \
	X(NET_WM_STATE_SKIP_TASKBAR,    ATOM_KNOWN, "_NET_WM_STATE_SKIP_TASKBAR") \
	X(NET_WM_STATE_SKIP_PAGER,      ATOM_KNOWN, "_NET_WM_STATE_SKIP_PAGER") \
	X(NET_WM_STATE_HIDDEN,          ATOM_KNOWN, "_NET_WM_STATE_HIDDEN") \
	X(NET_WM_STATE_FULLSCREEN,      ATOM_KNOWN, "_NET_WM_STATE_FULLSCREEN") \
	X(NET_WM_STATE_ABOVE,           ATOM_KNOWN, "_NET_WM_STATE_ABOVE") \
	X(NET_WM_STATE_BELOW,           ATOM_KNOWN, "_NET_WM_STATE_BELOW") \
	X(NET_WM_STATE_DEMANDS_ATTENTION, ATOM_KNOWN, "_NET_WM_STATE_DEMANDS_ATTENTION") \
	X(NET_WM_STATE_FOCUSED,         ATOM_KNOWN, "_NET_WM_STATE_FOCUSED") \
	/* ---- アクション ---- */ \
	X(NET_WM_ACTION_MOVE,           ATOM_KNOWN, "_NET_WM_ACTION_MOVE") \
	X(NET_WM_ACTION_RESIZE,         ATOM_KNOWN, "_NET_WM_ACTION_RESIZE") \
	X(NET_WM_ACTION_MINIMIZE,       ATOM_KNOWN, "_NET_WM_ACTION_MINIMIZE") \
	X(NET_WM_ACTION_SHADE,          ATOM_KNOWN, "_NET_WM_ACTION_SHADE") \
	X(NET_WM_ACTION_MAXIMIZE_HORZ,  ATOM_KNOWN, "_NET_WM_ACTION_MAXIMIZE_HORZ") \
	X(NET_WM_ACTION_MAXIMIZE_VERT,  ATOM_KNOWN, "_NET_WM_ACTION_MAXIMIZE_VERT") \
	X(NET_WM_ACTION_FULLSCREEN,     ATOM_KNOWN, "_NET_WM_ACTION_FULLSCREEN") \
	X(NET_WM_ACTION_CHANGE_DESKTOP, ATOM_KNOWN, "_NET_WM_ACTION_CHANGE_DESKTOP") \
	X(NET_WM_ACTION_CLOSE,          ATOM_KNOWN, "_NET_WM_ACTION_CLOSE") \
	/* ---- システムトレイ (XEmbed, SPEC §4.8) ---- */ \
	X(NET_SYSTEM_TRAY_OPCODE,       ATOM_KNOWN, "_NET_SYSTEM_TRAY_OPCODE") \
	X(NET_SYSTEM_TRAY_MESSAGE_DATA, ATOM_KNOWN, "_NET_SYSTEM_TRAY_MESSAGE_DATA") \
	X(NET_SYSTEM_TRAY_ORIENTATION,  ATOM_KNOWN, "_NET_SYSTEM_TRAY_ORIENTATION") \
	X(NET_SYSTEM_TRAY_VISUAL,       ATOM_KNOWN, "_NET_SYSTEM_TRAY_VISUAL") \
	X(XEMBED,                       ATOM_KNOWN, "_XEMBED") \
	X(XEMBED_INFO,                  ATOM_KNOWN, "_XEMBED_INFO") \
	/* ---- Motif / GTK ---- */ \
	X(MOTIF_WM_HINTS,               ATOM_KNOWN, "_MOTIF_WM_HINTS") \
	X(GTK_FRAME_EXTENTS,            ATOM_KNOWN, "_GTK_FRAME_EXTENTS") \
	X(GTK_SHOW_WINDOW_MENU,         ATOM_KNOWN, "_GTK_SHOW_WINDOW_MENU")

/* enum ATOM_xxx を生成 */
#define X(id, sup, str) ATOM_##id,
enum { ATOM_LIST(X) ATOM_COUNT };
#undef X

extern xcb_atom_t atoms[ATOM_COUNT];

void atoms_init(xcb_connection_t *conn);
/* _NET_SUPPORTED に載せるアトムの配列を組み立てる。戻り値は個数 */
uint32_t atoms_supported_list(xcb_atom_t *out, uint32_t max);
/* アトム値から enum を逆引き（_NET_WM_STATE の処理などで使う）。無ければ -1 */
int atoms_lookup(xcb_atom_t a);

#endif /* ATOMS_H */
